### PR TITLE
stdlib-list only for python < 3.10

### PR DESCRIPTION
**Pull request by thomas-brandstaetter**
• modify requirements to import stdlib-list when python version < 3.10
+ conditional import for stdlib-list

### CODE REVIEW

**Comment by thebjorn** [comment]
A better solution would be top remove the special casing at https://github.com/thebjorn/pydeps/blob/master/pydeps/pystdlib.py#L13 and just use the 0.9.0 version of stdlib-list and/or implement the suggestions in https://github.com/thebjorn/pydeps/issues/171

**Comment by thomas-brandstaetter** [comment]
I would prefer not to include an unnecessary, deprecated library if it's not needed, isn't used, and shouldn't even be used.

**Comment by thomas-brandstaetter** [comment]
I have a little concern about having three places asking for python version to decide whether include `stdlib_list` or not. I would put them into a central place defining two names like `stdlib_list_max_python_minor_version = 1 and put the version check into a boolean variable.

**Comment by thebjorn** [comment]
stdlib_list is no longer deprecated, it has been transferred to the pypa team :-)

**Comment by thebjorn** [comment]
Thanks, but the fundamental problem with the current workaround:
```
def pystdlib():
    """Return a set of all module-names in the Python standard library.
    """
    if sys.version_info[:2] >= (3, 10):
        # Python 3.10 has this functionality built-in.
        return list(sys.stdlib_module_names | set(sys.builtin_module_names))
    ...
```
is that it doesn't contain the full hierarchy of names (e.g. py3.11.3):
```
>>> import sys
>>> from stdlib_list import stdlib_list
>>> len(stdlib_list())
1027
>>> len(sys.stdlib_module_names | set(sys.builtin_module_names))
307
>>>
```
so the solution is to remove the workaround (especially now that stdlib-list is maintained by the pip-maintainers).

**Comment by thomas-brandstaetter** [comment]
I investigated some time in this. The difference between 

`list(sys.stdlib_module_names | set(sys.builtin_module_names))`

and 

`stdlib_list.stdlib_list`

is, that the latter includes submodules recursively which are not included in the first approach.

Since the work is done by stdlib_list, this pull request is outdated

**Comment by thomas-brandstaetter** [comment]
But, i want to remind you that your current implemented approach has 1 item more in the list than `stdlib_list` ones. `__main__` is in your list but not in `stdlib_list` 
[for_sharing.py.txt](https://github.com/thebjorn/pydeps/files/12114836/for_sharing.py.txt)

**Comment by thomas-brandstaetter** [comment]
`stdlib_list` already achieves what this pull request achieves.

**Pull request closed without merging**
